[package]
name = "easl_lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.121"
fsexp = { git = "https://github.com/Ella-Hoeppner/fsexp.git" }
tokio = { version = "1.38.0", features = ["rt-multi-thread", "io-std", "macros", "io-util"] }
easl = { git = "https://github.com/Ella-Hoeppner/easl.git" }
tower-lsp = "0.20.0"
unicode-segmentation = "1.11.0"
regex = "1.11.1"

[[bin]]
name = "easl_lsp"
path = "src/main.rs"
